const ACCESS_KEY= "AKIATSVGONKI3Q53AN54";
const SECRET_ACCESS_KEY= "ytyR4iRuHGNMXdsoQOOb92lBtJQG5C2ocS5vFwt";
const REGION= "us-west-2";

module.exports={
    ACCESS_KEY: ACCESS_KEY,
    SECRET_ACCESS_KEY:SECRET_ACCESS_KEY,
    REGION:REGION
};
