/** express-mailer configurations */
const MAIL_FROM = 'jinita.shah@openxcellinc.com';
const MAIL_PASSWORD = 'JinitaOpenGmail@19';
const MAIL_SERVICE = 'gmail';
const MAIL_HOST = 'smtp.gmail.com';
const MAIL_PORT = '465';
const MAIL_METHOD = 'SMTP';
const MAIL_SECURE = true;
const BUSI_AMOUNT = 0.2;
/** currently use server url */
const WEBURL = 'http://192.168.0.105:3001/web_api/';
// const WEBURL = 'http://jenkins.openxcell.info:9515/web_api/';

const AWSS3URL = 'https://varshalteamprivatebucket.s3.ap-south-1.amazonaws.com/';
const AWSS3PROJECTFOLDER = 'GunsBidCMS/';
const AWSS3PARTNERFOLDER = 'partner/';
const AWSS3EVENTFOLDER = 'event/';
const AWSS3BUSINESSFOLDER = 'business/';
const AWSS3PRODUCTFOLDER = 'product/';
const AWSS3PROMOTIONFOLDER = 'promotion/';
const AWSS3CATEGORYFOLDER = 'category/';
const AWSS3CATEGORYIMAGEFOLDER = 'image/';
const AWSS3MAINLAYOUTIMAGEFOLDER = 'main_layout_image/';
const AWSS3CATEGORYBANNERIMAGEFOLDER='category-banner-image/'
const AWSS3VIDEOFOLDER = 'video/';
const AWSS3DEALFOLDER = 'deal/';
const AWSS3BADGEFOLDER = 'badge/';
/** Use for JWT Authentication */
const JWTOBJCMS = {
	algo: 'HS512',
	secret: 'itstopsecret',
	expiresIn: '1h'
};

/** JWT sercret key for authentication */

const JWTTOKEN = "r<^l'{@v`/AKLPDN9*d}[R:y!w9k+4^%";

const MULTERFILEPATH = 'public/images/profile-pic';

module.exports = {
	MAIL_FROM: MAIL_FROM,
	MAIL_PASSWORD: MAIL_PASSWORD,
	MAIL_SERVICE: MAIL_SERVICE,
	MAIL_HOST: MAIL_HOST,
	MAIL_PORT: MAIL_PORT,
	MAIL_METHOD: MAIL_METHOD,
	MAIL_SECURE: MAIL_SECURE,
	WEBURL: WEBURL,
	JWTTOKEN: JWTTOKEN,
	JWTOBJCMS: JWTOBJCMS,
	LIMIT: 10,
	AWSS3URL: AWSS3URL,
	BUSI_AMOUNT: BUSI_AMOUNT,
	MULTERFILEPATH: MULTERFILEPATH,
	AWSS3PARTNERFOLDER:AWSS3PARTNERFOLDER,
	AWSS3PROMOTIONFOLDER: AWSS3PROMOTIONFOLDER,
	AWSS3EVENTFOLDER: AWSS3EVENTFOLDER,
	AWSS3BUSINESSFOLDER: AWSS3BUSINESSFOLDER,
	AWSS3PRODUCTFOLDER: AWSS3PRODUCTFOLDER,
	AWSS3VIDEOFOLDER: AWSS3VIDEOFOLDER,
	AWSS3PROJECTFOLDER: AWSS3PROJECTFOLDER,
	AWSS3DEALFOLDER: AWSS3DEALFOLDER,
	AWSS3BADGEFOLDER: AWSS3BADGEFOLDER,
	AWSS3CATEGORYFOLDER: AWSS3CATEGORYFOLDER,
	AWSS3CATEGORYBANNERIMAGEFOLDER: AWSS3CATEGORYBANNERIMAGEFOLDER,
	AWSS3CATEGORYIMAGEFOLDER: AWSS3CATEGORYIMAGEFOLDER,
	AWSS3MAINLAYOUTIMAGEFOLDER: AWSS3MAINLAYOUTIMAGEFOLDER
};
